version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mareimorsy/udagram-nginx
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: mareimorsy/udagram-api-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: mareimorsy/udagram-api-feed
  backend_feed_v0_1:
    build:
      context: ../../udacity-c3-restapi-feed-v0-1
    image: mareimorsy/udagram-api-feed:v0.1
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: mareimorsy/udagram-frontend
